const CONSTANTS = {
  LOCAL_STORAGE_KEY: "key-name",
  PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,50}$/,
  PROJECT_ROUTES: {
    AUTHTICATION: "/authentication",
    HOME: "/",
    GROUP: "/group",
    JOIN_GROUP: "/join-group",
    PROFILE: "/profile",
    LEGAL: "/legal",
    SUPPORT: "/support",
    OPEN_EXPENSES: "/openExpenses",
  },
  API_ROUTES: {
    GOOGLE_SIGN_IN: "/user/google-signin",
    SEND_LOGIN_OTP: "/user/login-send-otp",
    SEND_OTP: "/user/send-otp",
    LOGIN: "/user/login",
    REGISTER: "/user/register",
    ALL_GROUPS: "/group",
    GROUP_TYPE_LIST: "/group/groupTypeList",
    GROUP_DETAILS: "/group/single",
    GROUP_MEMBERS: "/group/members",
    ALL_EXPENSES: "/expense/getAllExpenses",
    ADD_EXPENSE: "/expense/addExpense",
    EDIT_EXPENSE: "/expense/editExpense",
    CREATE_GROUP: "/group/createGroup",
    JOIN_GROUP: "/group/joinGroup/",
    MY_PAIRS: "/group/myPairs/",
    DELETE_EXPENSE: "/expense",
    SW_SUBSCRIPTION: "/user/service-worker-subscribe",
    GROUP_SETTLEMENT: "/group/toggleGroupSettlement",
    GROUP_VISIBILITY: "/group/toggleGroupVisibilty",
    PROFILE_DETAILS: "/user",
    TOGGLE_AVAILIBILTY: "/user/toggleAvailibiltyStatus",
    UPDATE_PROFILE_DETAILS: "/user",
    GEN_NEW_AVATARS: "/user/generateAvatars",
    DOWNLOAD_GROUP_DATA: "/group/downloadGroupData",
    GROUP_LOGS: "/group/groupLogs",
    SPEND_ANALYSIS: "/group/spendAnalysis",
    FRIENDS_LIT: "/group/friendsList",
    ADD_GROUP_MEMBERS: "/group/addGroupMember",
    GET_SIMPLIFIED: "/group/simplified",
    LEAVE_GROUP: "/group/leaveGroup",
    GROUP_SETTINGS: "/group/groupSetting",
    GET_BUG_PRIOR_LIST: "/support/bug_priorities",
    GET_SUPPORT_CAT_LIST: "/support/support_cat",
    CREATE_TICKET: "/support",
    SERVER_HEALTH: "/health",
    TOGGLE_MEMBER_STATUS: "/group/toggleMemberStatus",
    UNREAD_STATUS: "/chat/unread-status",
    BUDGET_DETAILS: "/group/budgetDetails",
    SEND_REMINDER: "/group/sendReminder",
  },
  FONT_FAMILY: "Nunito",
};
export default CONSTANTS;
