import React from "react";
import LegalLayout from "./LegalLayout";

export default function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer">
      <p>
        <b>Hisabkar</b> is an <b>expense tracking and splitting</b> tool. We do <b>not process payments</b>, store financial credentials (like bank or
        card details), or move money between users in any way.
      </p>

      <h2>1. No Financial Responsibility</h2>
      <p>
        Hisabkar records shared expenses and calculates who owes whom — it does not settle payments on your behalf. We are <b>not responsible</b> for
        any financial disputes, incorrect entries, or unsettled balances between group members. Settling up (via UPI, cash, or any other method)
        happens entirely outside the app, between users.
      </p>

      <h2>2. User Responsibility</h2>
      <p>
        Users are <b>fully responsible</b> for verifying the accuracy of expenses they add and for actually settling their balances with other
        members. Hisabkar does not validate, enforce, or mediate any real-world transaction.
      </p>

      <h2>3. AI-Generated Content</h2>
      <p>
        The AI chat assistant can summarize spending or answer questions about your groups, but its responses are generated by a third-party AI model
        and <b>may be incomplete or inaccurate</b>. Nothing the assistant says should be treated as financial, tax, budgeting, or legal advice —
        always double-check figures against your actual expense records before acting on them.
      </p>

      <h2>4. Third-Party Services</h2>
      <p>
        Hisabkar relies on third-party services for parts of its functionality — Google for sign-in, an external provider for the AI assistant, and
        WhatsApp for optional expense/settlement sharing. We are not responsible for the availability, accuracy, or policies of these third-party
        services.
      </p>

      <h2>5. Data Privacy & Security</h2>
      <p>
        We take reasonable steps to secure stored expense data (see our <a href="/legal/privacy">Privacy Policy</a>), but users should avoid sharing
        sensitive financial details (like full account numbers) inside expense descriptions or group chat.
      </p>

      <h2>6. Service Availability</h2>
      <p>
        Hisabkar is maintained as an open-source, community-driven project. We don&apos;t guarantee uninterrupted uptime — the app or specific
        features (chat, AI assistant, notifications) may be temporarily unavailable for maintenance or reasons outside our control.
      </p>

      <h2>7. Open Source & No Warranty</h2>
      <p>
        Hisabkar is <b>open source</b>, developed for the community. The software is provided <b>&quot;as is&quot;</b>, without warranties of any kind
        regarding accuracy, reliability, or fitness for a particular purpose.
      </p>

      <h2>8. Changes to This Disclaimer</h2>
      <p>
        We may update this disclaimer as the app evolves. Material changes will be reflected here and, where relevant, on the app&apos;s{" "}
        <a href="/whats-new">What&apos;s New</a> page.
      </p>
    </LegalLayout>
  );
}
